#!/bin/bash
#Finds and deletes non-work related media files
sudo find /home . -name "*.mp3" -delete
sudo find /home . -name "*.mp4" -delete
sudo find /home . -name "*.wav" -delete
sudo find /home . -name "*.jpg" -delete
sudo find /home . -name "*.png" -delete
sudo find /home . -name "*.m4a" -delete
sudo find /home . -name "*.m4b" -delete
sudo find /home . -name "*.aif" -delete
sudo find /home . -name "*.iff" -delete
sudo find /home . -name "*.m3u" -delete
sudo find /home . -name "*.mid" -delete
sudo find /home . -name "*.mpa" -delete
sudo find /home . -name "*.wma" -delete
sudo find /home . -name "*.3g2" -delete
sudo find /home . -name "*.3gp" -delete
sudo find /home . -name "*.asf" -delete
sudo find /home . -name "*.avi" -delete
sudo find /home . -name "*.flv" -delete
sudo find /home . -name "*.m4v" -delete
sudo find /home . -name "*.mov" -delete
sudo find /home . -name "*.mpg" -delete
sudo find /home . -name "*.rm" -delete
sudo find /home . -name "*.srt" -delete
sudo find /home . -name "*.swf" -delete
sudo find /home . -name "*.vof" -delete
sudo find /home . -name "*.wmv" -delete
sudo find /home . -name "*.gif" -delete
#Finds potentially hazardous files
sudo find / . -name "*.html"
sudo find / . -name "*.php"
#Lists the html file in /var/www/html
cat /var/www/html/index.html
