#!/bin/bash
#This script was made by Clemence Yi.
#The purpose of this script is to greatly reduce the amount of time it takes to gain points in the Cyber Patriot competition.
#This script manages users, deletes potentially dangerous software, enables a firewall, manages services, does config management, manages network, and performs system updates.

#Updates the software lists
sudo apt-get update
#Lists all users
cat /etc/passwd
#Adds and deletes users
echo -n "How many users do you want to add? "
read addusers
count=1
while [ $count -le $addusers ]; do
	echo -n "Name of user? "
	read username
	sudo useradd $username -m
	count=$((count + 1))
done
echo -n "How many users do you want to delete? "
read deleteusers
count1=1
while [ $count1 -le $deleteusers ]; do
	echo -n "Name of user? "
	read username1
	sudo userdel $username1
	count1=$((count1 + 1))
done
#Manages sudo permissions
echo -n "How many users do you want to remove admin privileges from? "
read adminremove
count2=1
while [ $count2 -le $adminremove ]; do
	echo -n "Name of user? "
	read username2
	sudo deluser $username2 sudo
	count2=$((count2 + 1))
done
echo -n "How many users do you want to change passwords for? "
read passwdChange
count3=1
newPassword=""
while [ $count3 -le $passwdChange ]; do
	echo -n "Name of user? "
	read username3
	sudo chpasswd
	count1=$((count1 + 1))
done
#Removes potentially harmful software
sudo apt-get remove john netcat* bind9 telnet* iodine kismet medusa hydra fcrackzip ayttm empathy nitko logkeys vino tightvncserver rdesktop remmina vinagre rsync ettercap -y
sudo apt-get purge john netcat* bind9 telnet* iodine kismet medusa hydra fcrackzip ayttm empathy nikto logkeys vino tightvncserver rdesktop remmina vinagre rsync ettercap -y
sudo apt-get autoremove -y
#Gives a break before continuing
sleep 10
#Installs and enables ufw
sudo apt-get install ufw -y
sudo ufw enable
sudo ufw default allow outgoing 
sudo ufw default deny incoming
#Installs/removes various software
echo -n "Enable ssh? 1 for yes. "
read answer1
if [ $answer1 = 1 ]; then
	sudo apt-get install openssh-server -y
	sudo service ssh start
	sudo ufw allow 22/tcp
	sudo ufw allow 22
else
	sudo apt-get remove openssh-server -y
	sudo ufw deny 22/tcp
	sudo ufw deny 22
fi
echo -n "Enable vsftpd? 1 for yes. "
read answer2
if [ $answer2 = 1 ]; then
	sudo apt-get install vsftpd -y
	sudo service vsftpd start
	sudo ufw allow 21/tcp
	sudo ufw allow 21
else
	sudo apt-get remove vsftpd -y
	sudo ufw deny 21/tcp
	sudo ufw deny 21
fi
echo -n "Enable samba? 1 for yes. "
read answer3
if [ $answer3 = 1 ]; then
	sudo apt-get install samba -y
	sudo service smbd start
	sudo service samba start
	sudo ufw allow 445/tcp
	sudo ufw allow 445
else
	sudo apt-get remove samba -y
	sudo ufw deny 445/tcp
	sudo ufw deny 445
fi
echo -n "Enable Apache2? 1 for yes. "
read answer4
if [ $answer4 = 1 ]; then
	sudo apt-get install apache2 -y
	sudo service apache2 start
	sudo ufw allow 80/tcp
	sudo ufw allow 80
else
	sudo apt-get remove apache2 -y
	sudo ufw deny 80/tcp
	sudo ufw deny 80
fi
echo -n "Enable PHP? 1 for yes. "
read answer5
if [ $answer5 = 1 ]; then
	sudo apt-get install php5 -y
	sudo service php5 start
else
	sudo apt-get purge php5 -y
	sudo apt-get remove php5 -y
fi
echo -n "Enable mysql? 1 for yes. "
read answer5
if [ $answer5 = 1 ]; then
	sudo apt-get install mysql-server -y
	sudo service mysql start
else
	sudo apt-get purge mysql-server -y
	sudo apt-get remove mysql-server -y
fi
#This disables the root account login
sudo passwd -l root
#These commands copy config files to the desired location
sudo cp login.defs /etc
sudo cp sshd_config /etc/ssh
sudo cp common-password /etc/pam.d
sudo cp lightdm.conf /etc/lightdm
sudo cp common-auth /etc/pam.d
sudo cp sysctl.conf /etc
#Reloads sysctl
sudo sysctl -p

#Gives a quick break before upgrade
sleep 5
#Does an upgrade
sudo apt-get upgrade -y
#Reboots
sudo reboot
